// native/shared/motion_tokens.h: Glass Shell motion tokens for glassd (package P5).
// GENERATED by docs/phase2/research/springs.py --write. Do not edit by hand:
// change springs.py and re-run it (PLAN 1.5). Contract: docs/phase2/contracts/motion.md section 4.
// Header-only, C++17, no allocation.
#pragma once
#include <algorithm>
#include <cmath>

namespace lgs_motion {

inline constexpr const char *kVersion = "2428c76f74";

// A spring token (D2 11.2): SwiftUI Spring(duration d, bounce b), mass 1.
struct Token {
    const char *name;
    float d, b;        // perceptual duration (s), bounce
    float settleMs;    // CSS duration = settling time (|1 - x| <= 0.001)
    float t90Ms;       // time to 90 % of the travel
    float overshoot;   // peak overshoot, fraction of the travel
};

inline constexpr Token kInteractive{"interactive", 0.15f, 0.14f, 210.0f, 78.0f, 0.005f};  // press-in, drag smoothing, gamepad slider steps, pill lift
inline constexpr Token kHoverIn{"hover-in", 0.2f, 0.0f, 294.0f, 124.0f, 0.0f};  // hover light in, focus illumination in
inline constexpr Token kFade{"fade", 0.3f, 0.0f, 441.0f, 186.0f, 0.0f};  // hover and focus out, cross-fades, list insert, scrim
inline constexpr Token kSnappy{"snappy", 0.35f, 0.15f, 488.0f, 178.0f, 0.0063f};  // selection pill travel, toggle knob, toast in, release
inline constexpr Token kReleaseTouch{"release-touch", 0.4f, 0.25f, 510.0f, 178.0f, 0.0284f};  // direct hand poke only (unused with laser and gamepad)
inline constexpr Token kMorphOpen{"morph-open", 0.45f, 0.2f, 607.0f, 214.0f, 0.0152f};  // menu, popover, dropdown grows out of its source
inline constexpr Token kMorphClose{"morph-close", 0.3f, 0.0f, 441.0f, 186.0f, 0.0f};  // menu returns into its source
inline constexpr Token kSheetIn{"sheet-in", 0.5f, 0.0f, 735.0f, 310.0f, 0.0f};  // sheet or modal present; window materialize (glassd)
inline constexpr Token kSheetOut{"sheet-out", 0.35f, 0.0f, 514.0f, 217.0f, 0.0f};  // sheet dismiss
inline constexpr Token kPage{"page", 0.45f, 0.0f, 662.0f, 279.0f, 0.0f};  // route and tab content transitions
inline constexpr Token kDepth{"depth", 0.3f, 0.0f, 441.0f, 186.0f, 0.0f};  // z of popped crops and slabs (scene graph)
inline constexpr Token kTokens[] = {kInteractive, kHoverIn, kFade, kSnappy, kReleaseTouch, kMorphOpen, kMorphClose, kSheetIn, kSheetOut, kPage, kDepth};
inline constexpr int kTokenCount = 11;

// Linear ramps and fixed durations (ms).
inline constexpr float kMatInMs = 250.0f;  // small glass materialize (MO 3.2)
inline constexpr float kMatOutMs = 350.0f;  // small glass dematerialize (MO 3.2)
inline constexpr float kPageOutMs = 150.0f;  // old route content fades out (MO 4.12)
inline constexpr float kGlowOffMs = 90.0f;  // press glow off on release (MO 4.3)
inline constexpr float kSwapMs = 120.0f;  // label colour swap at t90 of a pill travel (MO 4.5)
inline constexpr float kReduceMs = 180.0f;  // the Reduce Motion cross-dissolve (MO C8)

// glassd phase policy (GM 5.2): covers and thick slabs ride these springs;
// other slabs ramp linearly in kMatInMs / kMatOutMs; Reduce Motion is a
// kReduceMs coverage fade with every optical term at its target.
inline constexpr const Token &kPhaseUp = kSheetIn;
inline constexpr const Token &kPhaseDown = kSheetOut;

// Materialize optics ramp: ranges of m (MO 9, GM 5.3).
struct Range { float a, b; };
inline constexpr Range kRampLight{0.0f, 0.6f};
inline constexpr Range kRampLens{0.0f, 0.7f};
inline constexpr Range kRampFrost{0.2f, 0.92f};
inline constexpr Range kRampTint{0.2f, 0.92f};
inline constexpr Range kRampShade{0.3f, 0.92f};
inline constexpr Range kRampShadow{0.4f, 1.0f};
inline constexpr Range kRampAlpha{0.0f, 0.3f};
inline float ramp(float m, Range r) { return std::clamp((m - r.a) / (r.b - r.a), 0.f, 1.f); }
inline float smoothstep01(float x) { x = std::clamp(x, 0.f, 1.f); return x * x * (3.f - 2.f * x); }
// Coverage alpha of a piece of glass at materialize progress m.
inline float coverage(float m) { return smoothstep01(ramp(m, kRampAlpha)); }

// MO 8: y = x - target with y(0) = y0, y'(0) = v0; t in seconds.
inline void spring(float y0, float v0, float t, float d, float b, float &y, float &v) {
    const float w = 2.f * 3.14159265358979f / d, z = b >= 0.f ? 1.f - b : 1.f / (1.f + b);
    if (std::fabs(z - 1.f) < 1e-6f) {  // critically damped
        const float e = std::exp(-w * t), B = v0 + w * y0;
        y = e * (y0 + B * t);
        v = e * (B - w * (y0 + B * t));
    } else if (z < 1.f) {  // underdamped
        const float wd = w * std::sqrt(1.f - z * z), e = std::exp(-z * w * t);
        const float B = (v0 + z * w * y0) / wd, c = std::cos(wd * t), s = std::sin(wd * t);
        y = e * (y0 * c + B * s);
        v = e * ((-z * w) * (y0 * c + B * s) + (-y0 * wd * s + B * wd * c));
    } else {  // overdamped
        const float q = std::sqrt(z * z - 1.f), r1 = -w * (z - q), r2 = -w * (z + q);
        const float A = (v0 - r2 * y0) / (r1 - r2), C = y0 - A;
        y = A * std::exp(r1 * t) + C * std::exp(r2 * t);
        v = A * r1 * std::exp(r1 * t) + C * r2 * std::exp(r2 * t);
    }
}
inline void spring(const Token &k, float y0, float v0, float t, float &y, float &v) { spring(y0, v0, t, k.d, k.b, y, v); }
// Settled (MO 8): |y| < 0.001 travel and |v| < 0.01 travel / d.
inline bool settled(float y, float v, float travel, float d) {
    return std::fabs(y) < 1e-3f * travel && std::fabs(v) < 1e-2f * travel / d;
}
// Progress of a 0 -> 1 step ms after it started; 1 from the settle on.
inline float sample(const Token &k, float ms) {
    if (!(ms > 0.f)) return 0.f;
    if (ms >= k.settleMs) return 1.f;
    float y, v;
    spring(k, -1.f, 0.f, ms / 1000.f, y, v);
    return 1.f + y;
}

}  // namespace lgs_motion
