#!/usr/bin/env python3
"""Build the Phase 2 UI font (Inter 4.1, SIL OFL 1.1) for in-memory injection.

  python docs/phase2/fontkit.py                    subset -> theme/fonts/InterVariable-lgs.woff2, print sizes
  python docs/phase2/fontkit.py --css OUT.css      also write the @font-face *.nowrap.css (base64 data: URI)
  python docs/phase2/fontkit.py --check            verify the subset (axes, features, coverage) and exit

Why a data: URI: the theme is injected as one <style> per Steam/SteamVR window and
nothing is ever written into Steam's files, so the font must travel inside the CSS.
Why a subset: every gamepadui window receives the whole bundle, so each KB counts.

Source: theme/fonts/InterVariable.woff2 (Inter 4.1 release, web/InterVariable.woff2,
352,240 bytes, sha256 693b77d4...a8e3) with its licence in theme/fonts/LICENSE.txt.
The OFL allows subsetting and embedding; Inter declares no Reserved Font Name, so the
subset may keep the name "Inter". We still register it under the private family name
"LGS Inter" so it can never collide with an Inter that a page or the system provides.

The design rules for using it are in docs/phase2/DESIGN2.md §5.
"""
import argparse
import base64
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "theme", "fonts", "InterVariable.woff2")
OUT = os.path.join(ROOT, "theme", "fonts", "InterVariable-lgs.woff2")

# Western and Central European Latin, Greek, Russian/Ukrainian Cyrillic, punctuation,
# euro/rupee/rouble, arrows and a few math signs: 121 KB as WOFF2 with both axes.
# Measured alternatives (2026-10-07): adding Vietnamese, IPA and Latin Extended-B/Additional
# doubles the file (229 KB); pinning opsz saves 42 KB but loses the display cut for titles.
# CJK, Thai, Arabic, Hebrew, Vietnamese etc. are NOT here on purpose: those codepoints fall
# through to Steam's own font stack (Motiva Sans and its per-language fallbacks), and
# DESIGN2.md §5.2 (step 4) keeps Steam's stack for languages that would otherwise mix fonts.
UNICODES = (
    "U+0000-00FF,U+0100-017F,U+0192,U+0218-021B,U+02C6-02C7,U+02D8-02DD,U+0300-0308,"
    "U+030A-030C,U+0326-0328,U+0370-03FF,U+0400-045F,U+0490-0491,U+2000-206F,U+20AC,"
    "U+20B9,U+20BD,U+2122,U+2190-2193,U+2212,U+2215,U+2248,U+2260,U+2264-2265,U+FEFF,U+FFFD"
)
# OpenType features kept. tnum: clocks, battery %, prices, download sizes.
# case: punctuation centred on capitals. calt/kern/ccmp/locl/mark/mkmk: Inter defaults.
FEATURES = "kern,calt,ccmp,locl,mark,mkmk,case,tnum"

FACE = """/* Phase 2 UI font: Inter 4.1 (c) 2016 The Inter Project Authors, SIL Open Font License 1.1
   (theme/fonts/LICENSE.txt). Subset {ranges} - generated by docs/phase2/fontkit.py,
   do not edit by hand. Private family name so it never collides with a page's own Inter.
   unicode-range lets every other script fall through to Steam's own fonts. */
@font-face {{
  font-family: "LGS Inter";
  src: url(data:font/woff2;base64,{b64}) format("woff2");
  font-weight: 100 900;
  font-style: normal;
  font-display: block;
  unicode-range: {ranges};
}}
"""

# The --lgs-font sweep (DESIGN2 §5.2 step 4). Steam sets "Motiva Sans" explicitly on
# many module classes and Arial on form controls (which do not inherit font-family in
# Chromium), so a body rule alone is not enough: every element in body takes the token,
# except monospace runs. Measured 2026-10-07 on main, bar, barpopup, keyboard,
# notifications, tooltip, frame.menu and vr:systemui: the only families in use are
# "Motiva Sans" stacks and Arial (inputs); no icon font is text-rendered.
SWEEP = """
/* --lgs-font sweep: one face everywhere, Steam's stack after it (tokens.md §4) */
html.lgs-on body {
  font-family: var(--lgs-font);
  font-synthesis: none;
  font-optical-sizing: auto;
  -webkit-font-smoothing: antialiased;
}
/* (0,3,2): beats Steam's module rules, the strongest measured being
   ".BasicUI .A .B" (0,3,0); areas never set another family */
html.lgs-on.lgs-on.lgs-on body :where(:not(code, pre, kbd, samp, tt, code *, pre *, kbd *, samp *)) {
  font-family: var(--lgs-font);
}
"""


def subset():
    from fontTools import subset as fts
    opts = fts.Options()
    opts.flavor = "woff2"
    opts.layout_features = FEATURES.split(",")
    opts.name_IDs = ["*"]          # keep copyright/licence name records (OFL requires the notice)
    opts.name_legacy = True
    opts.name_languages = ["*"]
    opts.notdef_outline = True
    opts.hinting = False           # CEF on the Frame renders unhinted, antialiased
    opts.desubroutinize = True
    font = fts.load_font(SRC, opts)
    sub = fts.Subsetter(opts)
    sub.populate(unicodes=fts.parse_unicodes(UNICODES))
    sub.subset(font)
    buf = io.BytesIO()
    fts.save_font(font, buf, opts)
    data = buf.getvalue()
    with open(OUT, "wb") as f:
        f.write(data)
    return data


def check(path):
    from fontTools.ttLib import TTFont
    f = TTFont(path)
    axes = {a.axisTag: (a.minValue, a.maxValue) for a in f["fvar"].axes}
    feats = sorted({fr.FeatureTag for fr in f["GSUB"].table.FeatureList.FeatureRecord}
                   | {fr.FeatureTag for fr in f["GPOS"].table.FeatureList.FeatureRecord})
    cmap = f.getBestCmap()
    probe = "Liquid Glass ÅÉÎõü ĀŁŒŠ Ελληνικά Кириллица Їжак 0123456789 €£¥ → − ≤"
    missing = sorted({c for c in probe if c != " " and ord(c) not in cmap})
    print(f"{path}: {os.path.getsize(path):,} bytes, {len(f.getGlyphOrder()):,} glyphs, "
          f"{len(cmap):,} codepoints")
    print(f"  axes {axes}")
    print(f"  features {' '.join(feats)}")
    print(f"  probe missing: {missing or 'none'}")
    copyright_ = f["name"].getDebugName(0)
    print(f"  name ID 0: {copyright_}")
    return not missing and "wght" in axes and "opsz" in axes


def main(argv):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--css", help="write the @font-face nowrap stylesheet here")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    if a.check:
        return 0 if check(OUT) else 1
    data = subset()
    b64 = base64.b64encode(data).decode("ascii")
    print(f"source {os.path.getsize(SRC):,} B -> subset {len(data):,} B -> base64 {len(b64):,} B")
    ok = check(OUT)
    if a.css:
        css = FACE.format(b64=b64, ranges=UNICODES.replace(",", ", ")) + SWEEP
        with open(a.css, "w", encoding="utf-8", newline="\n") as f:
            f.write(css)
        print(f"wrote {a.css} ({len(css):,} bytes)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
