#!/usr/bin/env python3
"""Build device/vr/systemui.asspod.js from the assPod's ES modules in device/asspod/src.

The daemon installs SteamVR page scripts as one function expression, (function (ctx) {...}), so
the modules are wrapped into a tiny module table: each import becomes a lookup and each export an
assignment. Exported functions are assigned at the top of their module (they are hoisted), so the
one import cycle (main-menu <-> search) resolves; other exports are assigned at the end.

Only the forms the sources use are accepted, one per line:
  import { a, b as c } from './x.js';     import * as ns from './x.js';
  export function f(...) / export async function f(...) / export default function f(...)
  export const|let|class X
Anything else at the start of a line that says import or export is an error.

  python tools/build_asspod.py           write the bundle
  python tools/build_asspod.py --check   exit 1 if the committed bundle is out of date
"""
import os
import posixpath
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "device", "asspod", "src")
OUT = os.path.join(ROOT, "device", "vr", "systemui.asspod.js")
ENTRY = "main.js"
FLAG = "assPod"

IMPORT_NAMED = re.compile(r"^import\s*\{([^}]*)\}\s*from\s*'([^']+)';\s*$")
IMPORT_NS = re.compile(r"^import\s+\*\s+as\s+(\w+)\s+from\s*'([^']+)';\s*$")
EXPORT_FN = re.compile(r"^export\s+(default\s+)?(async\s+)?function\s+(\w+)")
EXPORT_DECL = re.compile(r"^export\s+(const|let|class)\s+(\w+)")


def modules():
    out = {}
    for d, _, files in os.walk(SRC):
        for f in sorted(files):
            if f.endswith(".js"):
                p = os.path.join(d, f)
                out[os.path.relpath(p, SRC).replace(os.sep, "/")] = p
    return dict(sorted(out.items()))


def resolve(mod, spec):
    if not spec.startswith("."):
        raise SystemExit(f"{mod}: bare import {spec!r} (no packages in a page script)")
    return posixpath.normpath(posixpath.join(posixpath.dirname(mod), spec))


def transform(mod, src, known):
    early, late, body = [], [], []
    for n, line in enumerate(src.split("\n"), 1):
        m = IMPORT_NAMED.match(line)
        if m:
            target = resolve(mod, m.group(2))
            if target not in known:
                raise SystemExit(f"{mod}:{n}: no module {target}")
            names = []
            for part in [p.strip() for p in m.group(1).split(",") if p.strip()]:
                a = re.match(r"^(\w+)(?:\s+as\s+(\w+))?$", part)
                if not a:
                    raise SystemExit(f"{mod}:{n}: cannot read import {part!r}")
                names.append(a.group(1) if not a.group(2) else f"{a.group(1)}: {a.group(2)}")
            body.append(f"const {{ {', '.join(names)} }} = __req({target!r});")
            continue
        m = IMPORT_NS.match(line)
        if m:
            target = resolve(mod, m.group(2))
            if target not in known:
                raise SystemExit(f"{mod}:{n}: no module {target}")
            body.append(f"const {m.group(1)} = __req({target!r});")
            continue
        m = EXPORT_FN.match(line)
        if m:
            name = m.group(3)
            early.append(f"__e.{'default' if m.group(1) else name} = {name};")
            body.append(line[len("export "):].replace("default ", "", 1) if m.group(1) else line[len("export "):])
            continue
        m = EXPORT_DECL.match(line)
        if m:
            late.append(f"__e.{m.group(2)} = {m.group(2)};")
            body.append(line[len("export "):])
            continue
        if re.match(r"^\s*(import|export)\b", line):
            raise SystemExit(f"{mod}:{n}: unsupported module syntax: {line.strip()[:80]}")
        body.append(line)
    return "\n".join(early + body + late)


def build():
    mods = modules()
    if ENTRY not in mods:
        raise SystemExit(f"no {ENTRY} in {SRC}")
    parts = [
        f"// @lgs-flag {FLAG}",
        "// assPod for SteamVR's systemui page. GENERATED by tools/build_asspod.py from device/asspod/src;",
        "// edit the sources and run the tool, never this file. The daemon installs it as a page script",
        "// (device/lgs_shell.py vr_scripts) at window.__LGS_VRX.asspod; device/shell_ext/asspod.py drives it.",
        "(function (ctx) {",
        "  'use strict';",
        "  const __defs = Object.create(null);",
        "  const __mods = Object.create(null);",
        "  const __req = (id) => {",
        "    if (__mods[id]) return __mods[id];",
        "    const e = (__mods[id] = {});",
        "    __defs[id](e);",
        "    return e;",
        "  };",
    ]
    for mod, path in mods.items():
        with open(path, encoding="utf-8") as f:
            src = f.read()
        parts.append(f"  // ---------------------------------------------------------------- {mod}")
        parts.append(f"  __defs[{mod!r}] = function (__e) {{")
        parts.append(transform(mod, src, mods).rstrip())
        parts.append("  };")
    parts.append(f"  return __req({ENTRY!r}).default(ctx);")
    parts.append("})")
    return "\n".join(parts) + "\n"


def main():
    out = build()
    if "--check" in sys.argv[1:]:
        try:
            with open(OUT, encoding="utf-8") as f:
                cur = f.read()
        except OSError:
            cur = None
        if cur != out:
            print(f"{os.path.relpath(OUT, ROOT)} is out of date: run python tools/build_asspod.py")
            return 1
        print("assPod bundle up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(out)} bytes, {len(modules())} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
